CREATE TABLE "institucion" (
                               "idInstitucion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "nombreInstitucion" varchar,
                               "tipoInstitucion" varchar,
                               "nombrePersonaCargo" varchar,
                               "horaLlegada" time,
                               "folioPEmergencia" integer
);

CREATE TABLE "cuerpo" (
                          "idCuerpo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "nombreCuerpo" varchar,
                          "provincia" varchar,
                          "region" varchar,
                          "comuna" varchar
);

CREATE TABLE "compania" (
                            "idCompania" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "nombreCia" varchar,
                            "direccionCia" varchar,
                            "especialidad" varchar,
                            "idCuerpo" integer
);

CREATE TABLE "usuario" (
                           "idUsuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "nombreUsuario" varchar,
                           "contrasena" varchar,
                           "rol" varchar
);

CREATE TABLE "voluntario" (
                              "idVoluntario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "nombreVol" varchar,
                              "fechaNac" date,
                              "direccion" varchar,
                              "numeroContacto" varchar,
                              "tipoSangre" varchar,
                              "enfermedades" text,
                              "alergias" text,
                              "fechaIngreso" date,
                              "claveRadial" text,
                              "cargoVoluntario" text,
                              "rutVoluntario" varchar,
                              "idCompania" integer,
                              "idUsuario" integer
);

CREATE TABLE "inmueble" (
                            "idInmueble" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "direccion" varchar,
                            "tipoInmueble" varchar,
                            "estadoInmueble" text,
                            "folioPEmergencia" integer
);

CREATE TABLE "victima" (
                           "idVictima" SERIAL PRIMARY KEY,
                           "rutVictima" varchar,
                           "nombreVictima" varchar,
                           "edadVictima" integer,
                           "descripcion" text,
                           "folioPEmergencia" integer
);

CREATE TABLE "vehiculo" (
                            "idVehiculo" SERIAL PRIMARY KEY,
                            "patente" varchar,
                            "marca" varchar,
                            "modelo" varchar,
                            "tipoVehiculo" varchar,
                            "folioPEmergencia" integer
);

CREATE TABLE "movil" (
                         "idMovil" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "nomenclatura" varchar,
                         "especialidad" varchar,
                         "folioPEmergencia" integer
);

CREATE TABLE "emergencia" (
                              "idEmergencia" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "claveEmergencia" varchar,
                              "cuadrante" text,
                              "direccionEmergencia" varchar
);

CREATE TABLE "parte_emergencia" (
                                    "folioPEmergencia" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "tipoEmergencia" varchar,
                                    "horaInicio" time,
                                    "horaFin" time,
                                    "fechaEmergencia" date,
                                    "preInforme" text,
                                    "oficial" text,
                                    "idEmergencia" integer,
                                    "folioPAsistencia" integer
);

CREATE TABLE "parte_asistencia" (
                                    "folioPAsistencia" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "tipoLlamado" varchar,
                                    "aCargoDelCuerpo" varchar,
                                    "aCargoDeLaCompania" varchar,
                                    "fechaAsistencia" date,
                                    "horaInicio" time,
                                    "horaFin" time,
                                    "direccionAsistencia" varchar,
                                    "totalAsistencia" integer,
                                    "observaciones" text,
                                    "idMovil" integer
);

CREATE TABLE "materialP" (
                             "idMaterialP" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "llamarEmpresaQuimica" bool,
                             "clasificacion" varchar,
                             "nombreMaP" varchar,
                             "folioPEmergencia" integer
);

CREATE TABLE "parteEmergencia_voluntario" (
                                              "idParteVoluntario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              "folioPEmergencia" integer,
                                              "idVoluntario" integer
);

CREATE TABLE "parteAsistencia_voluntario" (
                                              "idParteAsistenciaVoluntario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              "folioPAsistencia" integer,
                                              "idVoluntario" integer
);

ALTER TABLE "institucion" ADD FOREIGN KEY ("folioPEmergencia") REFERENCES "parte_emergencia" ("folioPEmergencia");

ALTER TABLE "compania" ADD FOREIGN KEY ("idCuerpo") REFERENCES "cuerpo" ("idCuerpo");

ALTER TABLE "voluntario" ADD FOREIGN KEY ("idCompania") REFERENCES "compania" ("idCompania");

ALTER TABLE "voluntario" ADD FOREIGN KEY ("idUsuario") REFERENCES "usuario" ("idUsuario");

ALTER TABLE "inmueble" ADD FOREIGN KEY ("folioPEmergencia") REFERENCES "parte_emergencia" ("folioPEmergencia");

ALTER TABLE "victima" ADD FOREIGN KEY ("folioPEmergencia") REFERENCES "parte_emergencia" ("folioPEmergencia");

ALTER TABLE "vehiculo" ADD FOREIGN KEY ("folioPEmergencia") REFERENCES "parte_emergencia" ("folioPEmergencia");

ALTER TABLE "movil" ADD FOREIGN KEY ("folioPEmergencia") REFERENCES "parte_emergencia" ("folioPEmergencia");

ALTER TABLE "parte_emergencia" ADD FOREIGN KEY ("idEmergencia") REFERENCES "emergencia" ("idEmergencia");

ALTER TABLE "parte_emergencia" ADD FOREIGN KEY ("folioPAsistencia") REFERENCES "parte_asistencia" ("folioPAsistencia");

ALTER TABLE "parte_asistencia" ADD FOREIGN KEY ("idMovil") REFERENCES "movil" ("idMovil");

ALTER TABLE "materialP" ADD FOREIGN KEY ("folioPEmergencia") REFERENCES "parte_emergencia" ("folioPEmergencia");

ALTER TABLE "parteEmergencia_voluntario" ADD FOREIGN KEY ("folioPEmergencia") REFERENCES "parte_emergencia" ("folioPEmergencia");

ALTER TABLE "parteEmergencia_voluntario" ADD FOREIGN KEY ("idVoluntario") REFERENCES "voluntario" ("idVoluntario");

ALTER TABLE "parteAsistencia_voluntario" ADD FOREIGN KEY ("folioPAsistencia") REFERENCES "parte_asistencia" ("folioPAsistencia");

ALTER TABLE "parteAsistencia_voluntario" ADD FOREIGN KEY ("idVoluntario") REFERENCES "voluntario" ("idVoluntario");
